package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31-dev

import (
	"context"

	"go.infratographer.com/x/gidx"

	"go.infratographer.com/location-api/internal/ent/generated"
)

// FindLocationByID is the resolver for the findLocationByID field.
func (r *entityResolver) FindLocationByID(ctx context.Context, id gidx.PrefixedID) (*generated.Location, error) {
	return r.client.Location.Get(ctx, id)
}

// FindResourceOwnerByID is the resolver for the findResourceOwnerByID field.
func (r *entityResolver) FindResourceOwnerByID(ctx context.Context, id gidx.PrefixedID) (*ResourceOwner, error) {
	return &ResourceOwner{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
